//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using OSGi.NET.Event;
using OSGi.NET.Listener;
using OSGi.NET.Service;

namespace OSGi.NET.Core.Root
{
    /// <summary>
    /// 框架内核，内核也作为一个Bundle，用来启动其他Bundle组件
    /// </summary>
    public interface IFramework : IBundle
    {
        /// <summary>
        /// 初始化
        /// </summary>
        void Init();

        /// <summary>
        /// 获取所有Bundle模块
        /// </summary>
        /// <returns>所有已装载Bundle列表</returns>
        IList<IBundle> GetBundles();
    }
}

