//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OSGi.NET.Core
{
    /// <summary>
    /// Bundle激活器
    /// </summary>
    public interface IBundleActivator
    {
        /// <summary>
        /// 激活器启动
        /// </summary>
        /// <param name="context"></param>
        void Start(IBundleContext context);

        /// <summary>
        /// 激活器停止
        /// </summary>
        /// <param name="context"></param>
        void Stop(IBundleContext context);

    }
}
